# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-21 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0026_auto_20170629_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
